version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 42s8DkMVn.LskdEm2t(d
